export default class Powers {

	// This class stores the special powers generated by double dice rolls. 

	constructor() {
	this.powers = [];
	this.availablePowers = ['Increases health by 100',
		'Decreases opponents health by 100',
		'Increases strength between 1 - 100',
		'Decreases strength between 1 - 100',
		'Hides (Skips a go)',
		'Steals 50% of the strength from the opponent'];
	}

	setPowers(numberThrown) {
		this.powers = [];

		for(let count=0; count<= numberThrown-1; count++){
			this.powers.unshift(this.availablePowers[count]);
		}
	}

	clearPowers() {
		this.powers = [];
	}

	getPowers(){
		return this.powers;
	}

	getNumberOfPowersAssigned(){
		return this.powers.length;
	}
};